#!/bin/bash
# BMW Dashboard Deployment Script
# This script helps deploy the BMW car price prediction dashboards to Streamlit Cloud

echo "🚀 BMW Dashboard Deployment Guide"
echo "================================="
echo ""
echo "Your dashboards are now ready for deployment to Streamlit Cloud!"
echo ""
echo "📋 Deployment Steps:"
echo "1. Go to https://share.streamlit.io/"
echo "2. Sign in with your GitHub account"
echo "3. Click 'New app'"
echo "4. Select your repository: zayasinha/mltest"
echo "5. Set the main file path:"
echo ""
echo "   For ML Performance Dashboard:"
echo "   - File path: ml_dashboard_deploy.py"
echo "   - URL will be: https://[your-app-name].streamlit.app/"
echo ""
echo "   For Data Exploration Dashboard:"
echo "   - File path: data_dashboard_deploy.py"
echo "   - URL will be: https://[your-app-name].streamlit.app/"
echo ""
echo "6. Click 'Deploy'"
echo ""
echo "✨ Features of the deployment-ready dashboards:"
echo "- Automatic fallback to sample data if artifacts are missing"
echo "- Optimized for cloud deployment"
echo "- Professional BMW branding"
echo "- All visualizations working"
echo "- Error handling for missing files"
echo ""
echo "📊 Dashboard URLs (after deployment):"
echo "- ML Performance: https://[ml-dashboard-name].streamlit.app/"
echo "- Data Exploration: https://[data-dashboard-name].streamlit.app/"
echo ""
echo "🔗 Update your README.md with these live URLs!"
echo ""
echo "Need help? Check the Streamlit Cloud documentation:"
echo "https://docs.streamlit.io/streamlit-cloud"